version: '3.8'

services:
  flutter:
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    build:
      context: ./flutter
      dockerfile: Dockerfile
      args:
        - BASE_IMAGE_TAG=${BASE_IMAGE_TAG}
        - USER_NAME=${USER_NAME}
        - FLUTTER_VERSION=${FLUTTER_VERSION}
        - ANDROID_COMMAND_LINE_TOOLS_VERSION=${ANDROID_COMMAND_LINE_TOOLS_VERSION}
        - ANDROID_API_LEVEL=${ANDROID_API_LEVEL}
        - ANDROID_SDK_BUILD_TOOLS_VERSION=${ANDROID_SDK_BUILD_TOOLS_VERSION}
    volumes:
      - home:/home
    user: ${USER_NAME}
    stdin_open: true
    tty: true

volumes:
  home:
    name: ${VOLUME_NAME}

networks:
  default:
    name: ${NETWORK_NAME}